### DISCUSSION TITLE
New release

### DISCUSSION THREAD

**Discussion by PedroKTFC** [PedroKTFC/esphome-tesla-ble#16] [Announcements]
This release includes several new sensors and polling/sleeping parameters. Please see the readme for details.

Note one of the parameters allows you to specify a minimum time that the car and ESP are disconnected before sensors are set Unknown, ble_disconnected_min_time. However, currently it is not working as expected. I have set the default to 10s but, if this doesn't work for you, setting it to 0 will reinstate the original behaviour.

**Comment by PedroKTFC** [comment]
I believe I've resolved the issue with the minimum time to set sensors Unknown and I've updated the main branch with it.

**Comment by funnyfrish** [comment]
Thank you very much for your effort. Im using your repo with my esp32-s3. It works as expected. Thank you very much.
it would be nice when you include the charge poort open close functionality. We need also the Battery SOC. With those functionalities we dont need to use the tesla api anymore for evcc

**Reply by lukej0** [reply]
I think the state of charge is already available.
![grafik](https://github.com/user-attachments/assets/9b8799d9-16aa-422b-8012-2b90b4f48b5a)

**Reply by funnyfrish** [reply]
You right. Charge level is already there. Climate control and charge port open/close would be nice

**Reply by PedroKTFC** [reply]
I have started looking at these. Watch this space!

**Reply by PedroKTFC** [reply]
I've now updated the dev branch with controls for the charge port door, climate, sentry mode and steering wheel heat. I've done some limited testing but this is currently very much in the alpha testing stage. Any feedback welcome.

**Reply by lukej0** [reply]
Hi,

I tried installing it, but unfortunately it's throwing some errors and failing to install.

Logs:
```
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp: In lambda function:
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1430:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1430 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1439:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1439 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1443:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1443 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1447:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1447 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1451:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1451 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1455:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1455 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1459:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1459 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1463:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1463 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
Compiling .pioenvs/tesla-ble/src/esphome/components/text_sensor/text_sensor.cpp.o
*** [.pioenvs/tesla-ble/src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp.o] Error 1
========================= [FAILED] Took 65.48 seconds =========================
```

**Reply by PedroKTFC** [reply]
You also need to pick up the dev version of the library. Under packages try something like this:
```
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git@dev
```

**Reply by lukej0** [reply]
Sorry to bother you (all) again. Unfortunatelly I can't manage to get it to work.

This:
```
packages:
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev
  # listener: github://pedroktfc/esphome-tesla-ble/packages/listener.yml@main # Uncomment this to scan find your VIN BLE MAC address
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git@dev
```

Leads to:
```
INFO ESPHome 2025.4.2
INFO Reading configuration /config/esphome/tesla-ble-1fc824.yaml...
Failed config

packages: [source /config/esphome/tesla-ble-1fc824.yaml:102]
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev
  
  Shorthand only for strings.
  libraries: 
    - https://github.com/PedroKTFC/tesla-ble.git@dev
```

I'm pretty sure it's because of my really limited knowledge about all this programming-stuff. If anybody could point me in the right direction, I would appreciate it and I am willing to improve myself

**Comment by funnyfrish** [comment]
same here. Getting compile errors:
ompiling .pioenvs/tesla-ble-s3/src/esphome/core/component_iterator.cpp.o
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp: In lambda function:
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1430:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1430 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1439:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?
 1439 |           return_code = tesla_ble_client_->buildCarServerVehicleActionMessage (
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            buildCarServerActionMessage
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:1443:44: error: 'class TeslaBLE::Client' has no member named 'buildCarServerVehicleActionMessage'; did you mean 'buildCarServerActionMessage'?


this is my yaml on my esp32-s3. it was working with the main branch:
I think there is a mismatch on the dependencies on dev and main. @PedroKTFC Thank you for your work

```
substitutions:
  espidf_version: 5.3.0
  platformio_version: 6.8.1
  friendly_name: Tesla BLE Model Y
  device_name: tesla-ble
  device_description: Tesla BLE
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

esphome:
  name: tesla-ble-s3
  name_add_mac_suffix: false
  friendly_name: Tesla-BLE-S3

api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Tesla-Ble-S3 Fallback Hotspot"
    password: "xxxxxxxxxxx"
web_server:
  version: 3
  

external_components:
  - source: 
      type: git
      url: https://github.com/PedroKTFC/esphome-tesla-ble
      ref: dev


packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@dev
  #device_base: github://PedroKTFC/esphome-tesla-ble/boards/m5stack-atoms3.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@dev
  #listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

dashboard_import:
  package_import_url: github://PedroKTFC/esphome-tesla-ble/tesla-ble-esp32-generic.dashboard.yml@dev
  
tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
```

**Reply by PedroKTFC** [reply]
You don't seem to have the line in to pick up the dev version of the library.

**Comment by nagyrobi** [comment]
With 
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/PedroKTFC/esphome-tesla-ble
      ref: dev
    components: [tesla_ble_vehicle, tesla_ble_listener]

esphome:
  ...
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git@dev
```
I get
 ```
INFO ESPHome 2025.4.2
INFO Reading configuration /root/config/evse1_display.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing evse1 (board: esp32-s3-devkitc-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
Removing unused dependencies...
SemanticVersionError: Invalid simple block 'dev'
```

**Reply by PedroKTFC** [reply]
Have you cleaned the build files?

**Reply by funnyfrish** [reply]
You cant use dev as branch ind librariea. Only fixed tags e.g. 1.0.0 are allowed. İ have cleaned the build cache many times.ich think you have to push the changes of the librariea to the main branch.

**Reply by nagyrobi** [reply]
[Yes](https://esphome.io/components/esphome.html#libraries), or make a pre-release from that branch with a temporary tag.

**Reply by lukej0** [reply]
I thought I took on step further but it also crashed before completing.
My config (excerpt). The hash referencing to the last commit:

```
esphome:
...
  #dev library
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#0f5e81d
```

lead to:
```
Compiling .pioenvs/tesla-ble/libcc1/TeslaBLE/peer.o
.piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:873:7: error: no declaration matches 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
  873 |   int Client::buildCarServerVehicleActionMessage (int32_t set_value,
      |       ^~~~~~
.piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:873:7: note: no functions named 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
In file included from .piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:28:
.piolibdeps/tesla-ble/TeslaBLE@src-e4cc99ba679295027b4ca6424de1362f/include/client.h:22:9: note: 'class TeslaBLE::Client' defined here
   22 |   class Client
      |         ^~~~~~
*** [.pioenvs/tesla-ble/libcc1/TeslaBLE/client.o] Error 1
========================= [FAILED] Took 176.93 seconds =========================
```

**Reply by mr-p666** [reply]
Unfortunately, the same thing here.

**Reply by PedroKTFC** [reply]
I'm away tonight I'm afraid. I'll promote to main tomorrow evening. I find the pointing to GitHub very imprecise.

**Reply by funnyfrish** [reply]
Hopefully tomorrow then. Thx for your help

**Reply by top-gun** [reply]
The correct syntax for the library location is https://github.com/PedroKTFC/tesla-ble.git#dev, not https://github.com/PedroKTFC/tesla-ble.git@dev . For those running HA ESPhome Add-On, applying the change is tricky, because the library is linked in an enumeration, and afaik you can't use substitute to overwrite an enumeration.

As a workaround, i made a fork that includes the fixed line in base.yaml. You can compile off my GitHub repo by diverting your packages URL to:

github://top-gun/esphome-tesla-ble-test@dev4

and later on revert to the current address when PedroKTFC has had the time to implement his final solution.

Or you wait until PedroKTFC either applies PR#19 https://github.com/PedroKTFC/esphome-tesla-ble/pull/19 to his dev branch, or updates the main line library code to the new release. 

Anyway, the current release in the main branch is pretty good and these improvements are welcome, but waiting a day or two won't hurt us. I'm very happy to see so much progress on the ESP32 implementation of the vehicle control API :) 

A word of caution on the dev-branch: There is a minor change that may be breaking for you: The charger switch control used to be xxx_charger_switch. Now, it's xxx_charger. You may need to adjust your automations with the new control name. This is easy to fix, but you need to do it yourself.

**Reply by nagyrobi** [reply]
Thanks @top-gun it's building fine now for me on ESPHome 2025.5.0 with:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/PedroKTFC/esphome-tesla-ble
      ref: dev
    components: [tesla_ble_vehicle, tesla_ble_listener]

esphome:
  ...
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev
```

**Reply by top-gun** [reply]
> Thanks @top-gun it's building fine now for me on ESPHome 2025.5.0 with:
> 
> ```yaml
> external_components:
>   - source:
>       type: git
>       url: https://github.com/PedroKTFC/esphome-tesla-ble
>       ref: dev
>     components: [tesla_ble_vehicle, tesla_ble_listener]
> 
> esphome:
>   ...
>   libraries:
>     - https://github.com/PedroKTFC/tesla-ble.git#dev
> ```

Did that finish for you? The build went pretty far for me, then it ended with 

`Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ref.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-sse41.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_generichash/blake2b/ref/blake2b-ref.o
.piolibdeps/tesla-ble-f549c4/TeslaBLE/src/client.cpp:873:7: error: no declaration matches 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
  873 |   int Client::buildCarServerVehicleActionMessage (int32_t set_value,
      |       ^~~~~~
.piolibdeps/tesla-ble-f549c4/TeslaBLE/src/client.cpp:873:7: note: no functions named 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
In file included from .piolibdeps/tesla-ble-f549c4/TeslaBLE/src/client.cpp:28:
.piolibdeps/tesla-ble-f549c4/TeslaBLE@src-e4cc99ba679295027b4ca6424de1362f/include/client.h:22:9: note: 'class TeslaBLE::Client' defined here
   22 |   class Client
      |         ^~~~~~
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_hash/crypto_hash.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_hash/sha256/hash_sha256.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_hash/sha512/hash_sha512.o
Compiling .pioenvs/tesla-ble-f549c4/libeb3/libsodium/crypto_onetimeauth/crypto_onetimeauth.o
*** [.pioenvs/tesla-ble-f549c4/lib3cf/TeslaBLE/client.o] Error 1
========================= [FAILED] Took 50.75 seconds =========================`

I guess the addition to the yaml does not replace the entry, just adds another one to the enumeration. So it loads both libraries and this leads to a collision. 

The alternate branch of esphome-tesla-ble works for now. github://top-gun/esphome-tesla-ble-test@dev4

**Comment by PedroKTFC** [comment]
I've commented out the libraries specification in base.yml in the dev branch so hopefully there won't be a clash with what's in there and the esphome yaml file (see also https://github.com/esphome/issues/issues/3430 which suggests this is a known but unresolved issue). Despite this, if I validate my yaml I still get a duplication:
```
  libraries:
  - https://github.com/PedroKTFC/tesla-ble.git
  - https://github.com/PedroKTFC/tesla-ble.git#dev
```
I suspect this is caused by caching in github.

I'm proposing to make this permanent so that using any version of the library will be easy. This will mean that there will be a backward incompatibility since all yaml files will now need to specify the library:
```
esphome:
  ... existing stuff
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git # append #<branch etc> to get a different version
```
I think the inconvenience is outweighed by the greater flexibility this will provide.

I'll be interested if anyone who doesn't have caching issues finds this works (or doesn't!).

**Reply by nagyrobi** [reply]
Why do we need to manually specify the library in the yaml at all? Afaik most ESPHome components load the required libraries automatically.

**Reply by PedroKTFC** [reply]
I find the ESPHome documentation rather opaque at times so I can't answer your question fully. However, I'm pretty sure you have to specify any specific libraries that are needed somehow. As the tesla-ble library is an intimate part of this whole application, I want to ensure as much flexibility as possible. For most users it won't affect them once they've updated their yaml. If someone can propose a better way then I'll happily consider and change if it's easier and keeps the flexibility.

**Reply by nagyrobi** [reply]
Just a hint, their LVGL component downloads and installs the lvgl library in the background prior/during compile. I assume it's in their python part of the conponent.

**Reply by top-gun** [reply]
> Why do we need to manually specify the library in the yaml at all? Afaik most ESPHome components load the required libraries automatically.

Because it‘s the new hot sh… that is being made right now, not the stuff that has been included in the mainstream product for a long time and gets updated every few months. :)

**Comment by mr-p666** [comment]
Compiling on the dev branch works again, thanks!

**Reply by top-gun** [reply]
works for me, too :)

**Reply by lukej0** [reply]
Not working for me unfortunately. Seems, I have to stick to the main Version for now, unless anybody knows what to check.

config:
```
esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}

  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
    
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev

substitutions:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  name: tesla-ble
  friendly_name: "Tesla BLE v4"
  charging_amps_max: "16"
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

external_components:
  - source: github://pedroktfc/esphome-tesla-ble@dev

packages:
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev
  # listener: github://pedroktfc/esphome-tesla-ble/packages/listener.yml@main # Uncomment this to scan find your VIN BLE MAC address

dashboard_import:
  package_import_url: github://pedroktfc/esphome-tesla-ble/tesla-ble-esp32-generic.dashboard.yml@dev

tesla_ble_vehicle:
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
```

failure:
```
Compiling .pioenvs/tesla-ble/libcc1/TeslaBLE/peer.o
.piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:873:7: error: no declaration matches 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
  873 |   int Client::buildCarServerVehicleActionMessage (int32_t set_value,
      |       ^~~~~~
.piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:873:7: note: no functions named 'int TeslaBLE::Client::buildCarServerVehicleActionMessage(int32_t, pb_byte_t*, size_t*, int)'
In file included from .piolibdeps/tesla-ble/TeslaBLE/src/client.cpp:28:
.piolibdeps/tesla-ble/TeslaBLE@src-e4cc99ba679295027b4ca6424de1362f/include/client.h:22:9: note: 'class TeslaBLE::Client' defined here
   22 |   class Client
      |         ^~~~~~
*** [.pioenvs/tesla-ble/libcc1/TeslaBLE/client.o] Error 1
========================= [FAILED] Took 166.39 seconds =========================
```

To me it looks like esphome is still installing the main and the dev version of the libraries:
```
Library Manager: Installing git+https://github.com/PedroKTFC/tesla-ble.git
INFO Installing git+https://github.com/PedroKTFC/tesla-ble.git
git version 2.39.5
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-3o0akvkp'...
Library Manager: TeslaBLE@2.2.1+sha.7899a17 has been installed!
INFO TeslaBLE@2.2.1+sha.7899a17 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing nanopb/Nanopb @ ^0.4.91
INFO Installing nanopb/Nanopb @ ^0.4.91
Unpacking  [####################################]  100%
Library Manager: Nanopb@0.4.91 has been installed!
INFO Nanopb@0.4.91 has been installed!
Library Manager: Installing git+https://github.com/PedroKTFC/tesla-ble.git#dev
INFO Installing git+https://github.com/PedroKTFC/tesla-ble.git#dev
git version 2.39.5
Cloning into '/data/cache/platformio/cache/tmp/pkg-installing-hlcr6bwc'...
Library Manager: TeslaBLE@2.2.1+sha.0f5e81d has been installed!
INFO TeslaBLE@2.2.1+sha.0f5e81d has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
```
