### DISCUSSION TITLE
EVCC Custom Vehicle

### DISCUSSION THREAD

**Discussion by Trunks1982** [PedroKTFC/esphome-tesla-ble#2] [General]
Wenn einer EVCC nutzt und den ESP  zum steuern nutzen will, würde ich hier die yaml config posten.

**Comment by pvmil** [comment]
> Wenn einer EVCC nutzt und den ESP zum steuern nutzen will, würde ich hier die yaml config posten.

Did you proceed in making a working EVCC config?

**Comment by Trunks1982** [comment]
ja gerne:

`- name: Tesla_Model_3
  type: custom
  title: Tesla Model 3 # display name for UI
  capacity: 60 # battery capacity (kWh)
  phases: 3
  icon: car
  soc: # battery soc (%)
    source: http # plugin type
    uri: http://192.168.0.124:8123/api/states/sensor.tesla_ble_model3_charge_level
    method: GET
    headers:
      - Authorization: Bearer Token HA
    insecure: true
    jq: .state | tonumber
  
  status: # optional charge status (A..F)
    source: http # plugin type
    uri: http://192.168.0.124:8123/api/states/binary_sensor.tesla_ble_model3_charge_flap
    method: GET
    headers:
      - Authorization: Bearer Token HA
    jq: >-
      if .state == "on" or .state == "Eingesteckt" then "B"
      else null end
    insecure: true
  limitsoc: # optional in-vehicle limit soc, read-only (%)
    source: http # plugin type
    uri: http://192.168.0.124:8123/api/states/number.tesla_ble_model3_charging_limit
    method: GET
    headers:
      - Authorization: Bearer Token HA
    insecure: true
    jq: .state | tonumber
  maxcurrent:  # set charger max current (A)
    source: http # plugin type      
    uri: http://192.168.0.124:8123/api/services/number/set_value
    method: POST
    headers:
     - Authorization: Bearer Token HA
     - Content-Type: application/json
    body: "{\"entity_id\": \"number.tesla_ble_model3_charging_amps\", \"value\": \"${maxcurrent}\"}"
    insecure: true
 
  wakeup: # vehicle wake up command
    source: http
    uri: http://192.168.0.124:8123/api/states/button.tesla_ble_model3_wake_up
    jq: .state == "on"
    headers:
     - Authorization: Bearer  Token HA
  
  chargeenable:
    source: http
    uri: http://192.168.0.124:8123/api/services/switch/{{ if .chargeenable }}turn_on{{ else }}turn_off{{ end }}
    method: POST
    body: '{"entity_id": "switch.tesla_ble_model3_charger_switch"}'  
    headers:
     - Authorization: Bearer Token HA
     - Content-Type: application/json`

**Reply by pvmil** [reply]
Thanks, got it running 1st time configuring

**Reply by Trunks1982** [reply]
Mit dem Token haste hinbekommen?

**Reply by pvmil** [reply]
> Mit dem Token haste hinbekommen?

I created a long lived token in HA.

I don't completely understand what the value is of the status 'B' is / what the effect of that is

**Reply by Trunks1982** [reply]
genau so mit dem Token und dann einfach hinter Bearer setzen.

zum Thema "Status":
A = nicht verbunden
B = verbunden, aber nicht laden
C = laden

Der Rest wird dann automatisch ermitteln.

**Reply by pvmil** [reply]
It is also possible to add range and odometer 
Range shows the current range below the current charge percentage
Odometer value is shown in the configuration tab at the vehicle properties (not sure whether there is any other use for this)
```
    range:
      source: http # plugin type
      uri: http://192.168.0.124:8123/api/states/sensor.tesla_ble_range
      method: GET
      headers:
        - Authorization: "Bearer Token HA"
      insecure: true
      jq: .state | tonumber
    odometer:
      source: http # plugin type
      uri: http://192.168.0.124:8123/api/states/sensor.tesla_ble_odometer
      method: GET
      headers:
        - Authorization: "Bearer Token HA"
      insecure: true
      jq: .state | tonumber

```

**Reply by Trunks1982** [reply]
Jap.Hab ich auch alles eingefügt. Gebe alles an was möglich ist somit evcc alles benutzen kann.

**Comment by mr-p666** [comment]
Is anyone else experiencing incorrect readings from the charge current sensor?
I adjust the slider on the charging current controller and see the changes in the Tesla app. But I don't see any changes or incorrect readings via BLE.

**Comment by Trunks1982** [comment]
Jap würde sagen wird zu langsam oder gar nicht aktualiesiert beim laden. Hab 10s refresh.

**Reply by Trunks1982** [reply]
Ist falsch.1A Laden und 2A werden angezeigt.

**Comment by mr-p666** [comment]
Unfortunately... even if I change the controller to 0A, it still shows 2A.

**Reply by Trunks1982** [reply]
So jetzt ist das Auto vollgeladen und zeigt jetzt 0A an was ja wieder richtig ist.

**Reply by Trunks1982** [reply]
Bin gespannt ob jetzt gleich einschläft.

**Comment by Trunks1982** [comment]
@mr-p666 hast du das auch bei Evcc wenn Auto voll feladen ist das evcc immer noch die Amp‘s ändert und Auto so nicht einschlafen kann?

**Reply by mr-p666** [reply]
That's clear.
You have to build the logic for this into the control system. Ultimately, you might want to change the amperage for a future charge, and every control command either wakes the vehicle up or prevents it from falling asleep.

**Reply by Trunks1982** [reply]
Nein das kann man nicht einbauen.Das müsste wenn in der Esp Software geöndert werden das beim verstellen der amp nicht das auto aufgeweckt wird.Wenn ich mir es recht überlege macht es auch keinen Sinn das das auto jedesmal wieder aufwacht. Wenn es lädt ist er ja eh wach.

**Reply by mr-p666** [reply]
How is the ESP supposed to know whether the command should be transmitted now or not? Just because the vehicle isn't charging right now doesn't mean you don't want to change the amps. The same logic applies to the Tesla app. You can open it, read the data, but as soon as you change the amps, you automatically wake up your car.

And why would you want to change that beforehand? If, for example, I can only charge at 7A with solar power during the day, and the electricity price is low at night and I want to use the short window to pump in the full 16A, then I don't set an alarm to adjust the amps specifically for that.

Or, as I mentioned before, you control it via the control system and integrate the logic there, since the system knows exactly whether and how much power should be charged to the car and when.

**Reply by Trunks1982** [reply]
Ich glaub du verstehst nicht was ich meine in bezug auf evcc. Musst mal drauf achten wenn auto voll ist wird fleissig amp noch verändert und weckt das auto auf.

**Reply by Trunks1982** [reply]
Und wenn ich was verstellen will wecke ich das auto auf und setze den wert.

**Reply by mr-p666** [reply]
I don't use EVCC. But since there's a sensor that reports the current charging status, EVCC has to listen for it and not send updates once charging is complete.

**Reply by Trunks1982** [reply]
Eigentlich ja. Ist aber anscheinend nicht so. Könnte ich aber nochmal erfragen.

**Reply by pvmil** [reply]
I also see EVCC sending charging amps hours after charging has finished. Verified for todays charging. It was in PV mode. 
I agree this is not a esp issue, it is EVCC related. Can it be due to using the B charge status? (wich means connected not charging) I do not know what the effect is when it is set to C for example..

**Reply by Trunks1982** [reply]
Das kann ich dir nicht sagen. Um einzelne Status anzugeben bräuchten wir drei einzelne sensoren die true und false ausgeben. 

https://github.com/evcc-io/evcc/discussions/18746

**Reply by pvmil** [reply]
Hmmm Thanks for sharing. Possibly the answer is to get this configured (copy out of the mentioned issue)

status:
  source: combined
  plugged:
    source: ...
  charging:
    source: ...

**Reply by Trunks1982** [reply]
Kann gut sein. Die Punkte können wie gesagt nur true false lesen

**Reply by pvmil** [reply]
That is possible, I've configured it, I do not know how to test it now. Currently (PV mode, car connected, not charging) reports 'B' in the log which is right. Since the car is completely full I cannot get into a different charging state, I cannot perform additional tests the coming days :(

The config seems good however... @Trunks1982 can you try this?

```
status:
  source: combined
  plugged:
    source: http
    uri: http://192.HAIP:8123/api/states/binary_sensor.tesla_ble_1e53f4_charge_flap
    method: GET
    headers:
      - Authorization: "Bearer MyHAToken"
    insecure: true
    jq: .state == "on"
  charging:
    source: http
    uri: http://192.HAIP:8123/api/states/sensor.tesla_ble_1e53f4_charging_state
    method: GET
    headers:
      - Authorization: "Bearer MyHAToken"
    insecure: true
    jq: .state == "charging"
```

Charge_flap 'on', means open (so plugged), charging state speaks for itself
