### DISCUSSION TITLE
Boot and frunk controls now in dev

### DISCUSSION THREAD

**Discussion by PedroKTFC** [PedroKTFC/esphome-tesla-ble#33] [Announcements]
Dev now includes a switch to open and close the boot and a button to open the frunk. The latter is a button as you obviously can't close the frunk remotely.

Note you MUST also include the dev version of the tesla-ble library to build this successfully.

**Comment by funnyfrish** [comment]
Thank you very much. Thats really great

**Reply by funnyfrish** [reply]
İ couldnt find it. İm already on dev but nothing with frunk in the gui..

**Comment by PedroKTFC** [comment]
It might be a github caching issue. Unfortunately it can take up to 24 hours to get the most recent version unless you specify the _refresh:_ parameter (but even then I don't find it reliable or covers everything - eg you might not pick up the latest library although hopefully as I hadn't changed it for several days it should pick up the latest).

**Reply by top-gun** [reply]
@funnyfrish : If you run into issues with the library, it's possible to specify a specific github commit instead of a branch. Obviously, this is a last resort, and you should set it back to #dev as soon as possible, like the next day.

This definition will point to the current commit of the library:

```
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries: 
    - https://github.com/PedroKTFC/tesla-ble.git#d1e46a6
```

Don't forget to go back to the standard:

```
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries: 
    - https://github.com/PedroKTFC/tesla-ble.git#dev
```
