### DISCUSSION TITLE
latest tesla-ble-example.yml and error about $ in name

### DISCUSSION THREAD

**Discussion by Twiederh** [PedroKTFC/esphome-tesla-ble#46] [General]
Hi,
thank you for this project, I love it. I had an issue with the latest testable-example.yml yesterday that took me a while to figure out: when compiling in ESPhome, I received an error that 
'$' is an invalid character for names. Valid characters are: abcdefghijklmnopqrstuvwxyz0123456789-_ (lowercase, no spaces).

Since I was not sure where this was coming from, I replaced $(name) under esphome: with tesla-ble-a77e79, which then cost me some time to resolve because the mDNS name changed to tesla-ble-a77e79-a77e79 and I could not get a corrected version installed since the installer tried to connect to tesla-ble-a77e79.local via mDNS.

to resolve this, adding use_address: with the current IP address of the device helps to install a new image on the device via OTA.

The original issue seems to be that under substitutions device_name is declared but below in the esphome section name is used instead. After changing the line from name: ${name} to name: ${device_name} everything works.

I do not know if this only affects my setup but if it happens to someone else, the above might be helpful.

Many regards,
Thomas.

**Comment by PedroKTFC** [comment]
I'm not sure what's happening. Are you building in HA ESPHome? Can you post you're yaml?

**Reply by Twiederh** [reply]
Yes, I am using ESPHome as HA App.

This is essentially the current yaml from GitHub with just name replaced by device_name

```
substitutions:
  # all substitutions for this project
  espidf_version: 5.3.0
  platformio_version: 6.8.1
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.7.72

external_components:
  source: github://PedroKTFC/esphome-tesla-ble

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml
  #listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  libraries: 
    - https://github.com/PedroKTFC/tesla-ble.git
   
tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
```

This was the original yaml I was using:

```
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://PedroKTFC/esphome-tesla-ble@dev
  refresh: 1h

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries: 
    - https://github.com/PedroKTFC/tesla-ble.git#dev

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@dev
  listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml@dev # Uncomment this to scan find your VIN BLE MAC address

dashboard_import:
  package_import_url: github://PedroKTFC/esphome-tesla-ble/tesla-ble-esp32-generic.dashboard.yml@dev



tesla_ble_vehicle:
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 10s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  ble_disconnected_min_time: 60 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
  
substitutions:
  name: tesla-ble-6b9658
  friendly_name: Tesla BLE 6b9658
  name_add_mac_suffix: "False"
  charging_amps_max: "16"
  ble_mac_address: "7C:E2:69:FD:XX:XX"
  tesla_vin: "XP7YGCEK5RBXXXXXX"
```
I do notice that the below yaml uses ${name} and compiles without issues, I just have no clue why.

Edit: I have no clue why the single quotes do not work to mark the text as code.

One more thing: I need the use_address: 192.168.7.72, if I comment it out, ESPHome reports that the ESP32 is offline. I can ping the device using the mDNS address however. Very strange.

Oh, and one more thing: I changed the name_add_mac_suffix from false to true in the latest yaml, I just checked: if it is set to false then mDNS with the MAC address also does not work.
