### DISCUSSION TITLE
Charge port open without Bluetooth

### DISCUSSION THREAD

**Discussion by nagyrobi** [PedroKTFC/esphome-tesla-ble#58] [Ideas]
For those who want a quick way to just open the charge port and nothing else, without requiring an active Bluetooth connection, can use this:

```yaml
remote_transmitter:
  pin: GPIOXX
  carrier_duty_percent: 100%

button:
  - platform: template
    name: Charge port open via RF
    on_press:
      - remote_transmitter.transmit_raw:
          repeat:
            times: 10
            wait_time: 25ms
          code: [400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -1200, 400, -400, 400, -400, 800, -800, 400, -400, 800, -800, 800, -800, 400, -400, 800, -800, 800, -800, 800, -800, 800, -800, 800, -800, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 400, -400, 800, -400, 400, -400, 400, -800, 400, -400, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 800, -800, 400, -400, 400, -400, 400, -400, 800, -400, 400, -800, 400, -400, 800, -1200, 400, -400, 400, -400, 800, -800, 400, -400, 800, -800, 800, -800, 400, -400, 800, -800, 800, -800, 800, -800, 800, -800, 800, -800, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 400, -400, 800, -400, 400, -400, 400, -800, 400, -400, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 800, -800, 400, -400, 400, -400, 400, -400, 800, -400, 400, -800, 400, -400, 800, -1200, 400, -400, 400, -400, 800, -800, 400, -400, 800, -800, 800, -800, 400, -400, 800, -800, 800, -800, 800, -800, 800, -800, 800, -800, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 400, -400, 800, -400, 400, -400, 400, -800, 400, -400, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 800, -800, 400, -400, 400, -400, 400, -400, 800, -400, 400, -800, 400, -400, 400]
```

Code to be transmitted with a 433.92 MHz transmitter for Europe (315 MHz for USA). STX882 (recommended), or FS1000A (ymmv).

See [Remote Transmitter component](https://esphome.io/components/remote_transmitter) docs.
