### DISCUSSION TITLE
Don‘t use ESPHome Add-On 2025.6.0 or 2025.6.1

### DISCUSSION THREAD

**Discussion by top-gun** [PedroKTFC/esphome-tesla-ble#61] [General]
I just built the dev and main branches with 2025.6-beta2 of the add on. They compile, but the BLE signal strength is „unavailable“, everything else works. In the log I can see that every time the BLE signal strength is queried, a „GAP error code 26“ is logged instead.

Back to 2025.5.2, and everything works just fine.

**Comment by top-gun** [comment]
Update: 2025.6.0 is out, and it has the same issue: No BLE signal data, just an error message in the log file about an error code 26.

![image](https://github.com/user-attachments/assets/87349e0a-e0f2-48de-9f0a-172bfce19b47)

**Comment by top-gun** [comment]
Ok, I learned a few things while I tried to track this down:

1.) As of 2025.6.0, the default and stable ESP-IDF is no longer 5.2.2, it's 5.3.2. With no explicit version command, 5.3.2 will be used by ESPHome.
2.) We are no longer supposed to specify a certain platform version. ESPHome has its own fork of the platform/espressif framework. So the recommended configuration for ESP32 is now much simpler:

```
esp32:
  platform: esp32
  framework:
    type: esp-idf
    version: 5.3.2
```

But: This won't change the issue at hand. Chatgpt suggested two workarounds:
1.) Use 2025.5.2 as it's working fine.
2.) Use a different code to access rsi data. I will give that a try, but it's probably a better option not to mess with the code but wait for the developers to sort this out.

**Reply by top-gun** [reply]
Ok, this code in your Yaml file generates a nice interim sensor until 2025.6 gets fixed:

```
esp32_ble_tracker:
  max_connections: 3

sensor:
  - platform: ble_rssi
    mac_address: ${ble_mac_address}
    name: "RSSI via ble_rssi"
```

I haven't tried if this is compatible with the listener code to find a new car, maybe there are issues if both functions are active at the same time. And I'm sure this causes another increase in code size as it's a new functionality that needs to be included.

**Reply by PedroKTFC** [reply]
I'm puzzled as to what this sensor is replacing. Also, I'm always wary of bleeding edge releases. We need to be sure things work with any release that's recommended.

**Reply by top-gun** [reply]
> I'm puzzled as to what this sensor is replacing. Also, I'm always wary of bleeding edge releases. We need to be sure things work with any release that's recommended.

This sensor is broken with 2025.6.0:

<img width="414" alt="image" src="https://github.com/user-attachments/assets/2c606ba4-6f36-4855-b2d2-81a19e09e422" />

I‘m sure it will come back. What I showed is a workaround that is functional, but it bloats the image size by a hefty 200kB. Sticking with 2025.5.2 is imho the better option.

Otoh, what I understood is:

ESP IDF 5.3.2 is now the new gold standard for all ESP variants because it works well on every variety of ESP32.

and the ESPHome devs have deprecated the official Espressiv platformio frameworks in favour of their own pioarduino framework. This is not about bleeding edge, it‘s their new stable platform where we no longer need to match versions. So this is supposed to be all we use and need for version management:


```
esp32:
  board: esp32dev  # oder ein anderes passendes Board
  framework:
    type: esp-idf
    version: 5.3.2
```
The current pioarduino fw is compatible with all 5.x versions, even up to the 5.5 which is still in development.

**Reply by top-gun** [reply]
Ok, my ticket on Github got closed because the fix is already in the dev branch.

So, the best choice right now is to skip 2025.6.0 and wait for the next version.

**Reply by PedroKTFC** [reply]
What is your yaml? I want to try this out on my test system but I'm getting errors.

**Reply by top-gun** [reply]
If you check out this commit, it's working for me. I had to remove a few lines in board.yml.

https://github.com/top-gun/esphome-tesla-ble-test/tree/f2e1cd58b1544a9cadc8b949ff5b5b424e17475f

My yaml:

```
substitutions:
  # all substitutions for this project
  espidf_version: "5.3.2"
#  platformio_version: 6.9.0
  friendly_name: Tesla BLE F549C4
  device_name: tesla-ble-f549c4
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://top-gun/esphome-tesla-ble-test@dev


packages:
  base:  github://top-gun/esphome-tesla-ble-test/packages/base.yml@dev
  device_base: github://top-gun/esphome-tesla-ble-test/boards/esp32-generic.yml@dev
  client: github://top-gun/esphome-tesla-ble-test/packages/client.yml@dev
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev 
      
tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 180 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  ble_disconnected_min_time: 120 # Minimum time BLE must be disconnected before sensors are Unknwon (s)

```

**Reply by PedroKTFC** [reply]
I actually got it to work eventually. I need to update the yml files. It's on my to do list!

**Comment by top-gun** [comment]
Update: 2025.6.1 will not compile with the example config, there seems to be a breaking change about fixed_queue.

![image](https://github.com/user-attachments/assets/22d4ffad-72e8-427d-abfe-f3d92bf81979)

Bummer. 2025.5.2 works well.

2025.6.0 has the known issue with BLE Signal.

2025.6.1 won't compile at all.

Atm I'm scratching my head.

**Reply by top-gun** [reply]
Update: I opened a ticket on the esphome repo, and they told me we can't use overrides for the ESP-IDF and the framework anymore. I'm testing right now, and it seems this is again the issue. So the Yaml-branch with the changes to the ESP32-block is really the way to go.

**Reply by PedroKTFC** [reply]
Thanks for these updates. I was travelling all day yesterday so wasn't able to look at any of this. This morning I have successfully compiled using the yaml branch on my test system which doesn't connect to a car. Later I'll try it on my main system and car.

**Reply by top-gun** [reply]
Me too, I just finished a successful build with that branch plus the small changes I documented in my PR.


Update: Both ESP32 and ESP32-S3 compiled and worked flawlessly with the Yaml branch.

**Comment by PedroKTFC** [comment]
I have now updated the example in the yaml branch. I've tried to strip out everything that specifies a version, so it's slightly different to your pull request. It's worked in my two different systems. I want to copy it into dev if it works for you (and any others that try it), and then move dev into the main branch so everyone is up to date.

**Reply by jjjasont** [reply]
I've compiled yaml branch and it's working on my ESP32.
Compile without error.
Install without error in 2025.6.3
Sensors also working fine. Bluetooth signal strength is now back

**Reply by top-gun** [reply]
I had to do minor modifications:

- Added @yaml to all import addresses
- Pointed the API key to my secrets-file
- Changed the ESP32-block for my ESP32-S3

With these changes it's working just fine.

```

substitutions:
  # all substitutions for this project
  friendly_name: Tesla BLE
  device_name: "tesla-ble-s3"
  device_description: Tesla BLE
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

esp32:
  board: esp32-s3-devkitc-1  # set as needed for your board, see above
  variant: esp32s3   # set as needed for your board, see above
  flash_size: 8MB
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://PedroKTFC/esphome-tesla-ble@yaml

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@yaml
  common: github://PedroKTFC/esphome-tesla-ble/packages/common.yml@yaml
  project: github://PedroKTFC/esphome-tesla-ble/packages/project.yml@yaml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@yaml
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git

tesla_ble_vehicle:
  odometer: # miles by default, edit the entity in home assistant if you need km
    name: "Odometer" # Rename if desired
  battery_range: # miles by default, edit the entity in home assistant if you need km
    name: "Range"
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
```
