### DISCUSSION TITLE
New release 2025.1.0

### DISCUSSION THREAD

**Discussion by PedroKTFC** [PedroKTFC/esphome-tesla-ble#71] [Announcements]
I've updated the main branch from dev and I've decided to call it version 2025.1.0 as I hope this marks a reliable release. There are a few significant changes:
- Probably the one most likely to cause issues is the included yml files have changed. If you are no longer able to build, please look at the example yaml file. You should have all and only those `PedroKTFC` lines in your build. Also, the `esp32:` section is now more simple. Any issues please post them and I'll try to help.
- Any control requests are given priority over data requests so should happen more promptly
- Align more with https://github.com/Lenart12/TeslaBle2Mqtt-addon. This means some switches and buttons are now covers. The best way to see which is to look at the device display and, in the Controls section, covers look either like an open/close "thing" or an up/down arrow. Unfortunately this might introduce breaking changes for anyone who used the original types in automations etc. I can only apologies and hope the alignment will be worth it.
- New controls:
  - Defrost car (which in this heatwave seems the most ridiculous upgrade of all time!)
  - Unlock charge port
- New sensors:
  - Boot open/closed
  - Current limit setting
  - Defrost on/off
  - Frunk open/closed

**Comment by mrd0n** [comment]
Wonderful upgrade release!  Thank you very much for all of your time spent on this project.

**Comment by mrd0n** [comment]
Just wanted to share something that I realized adopting your fork and the latest release.  (Awesome evolution with so many API elements exposed!)

We have two tesla's, so two ESP32's to control and coordinate the charging with solar and between the two cars.  I previously had to break down the base and common yaml files to set unique VIN, BLE MAC address and api_encryption keys during the compile process.  

Today I realized that using the standard package definitions for VIN/MAC/Api_key works as follows!   The main.yaml substitutions replace the default secret definitions within the packages as long as the default secret names exist in the secrets.yaml file.  (e.g.   tesla_vin must exist in secrets.yaml, but gets replaced by ```tesla_vin: !secret tesla_vin_louie```

I know that there are a few folks here that have two cars, so hopefully this helps them.  (It's so cheap to add another esp32 device versus trying to re-write the system to have a single esp32 control multiple cars.

Here is a representation of my secrets.yaml and relevant section of the main yaml file:

```
#secrets.yaml:

#car 1
api_encryption_key_louie: "xxxxxxxx......="
ble_mac_address_louie: "xx:xx:xx:xx:xx:01" # vehicle BLE MAC address
tesla_vin_louie: "5YJ3XXXXXX" # vehicle VIN

#car 2
api_encryption_key_jinny: "pBhYbv/YHZYU8OffCgtYMPMNTy4a0c1NH7C/57U9XyM="
ble_mac_address_jinny: "xx:xx:xx:xx:xx:02" # vehicle BLE MAC address
tesla_vin_jinny: "7SAYXXXXX" # vehicle VIN

api_encryption_key: "blah-gets-replaced="
ble_mac_address: "blah-gets-replaced" # vehicle BLE MAC address
tesla_vin: "blah-get-replaced" # vehicle VIN
```

```
#main.yaml for car 1
substitutions:
  #car 1 (Louie)
  device_name: tesla-ble-68d2a4
  friendly_name: Tesla BLE - Louie
  device_description: Interact with Tesla vehicles over BLE using ESPHome and Home Assistant
  esphome_version: "2025.6.1"
  ble_mac_address: !secret ble_mac_address_louie
  tesla_vin: !secret tesla_vin_louie
  charging_amps_max: "32"
...
api:
  encryption:
    key: !secret api_encryption_key_louie
...
```
