### ISSUE TITLE
Pairing with a Model Y (2025)

### ISSUE THREAD

**Issue by Arjan444** [PedroKTFC/esphome-tesla-ble#11]
I can't seem to pair the BLE Module with the car. The car is a new Model Y (2025). 
Just wondering if anyone was able to pair the ESP32 M5NanoC6 (default configuration from Yoziru) with a new Model Y.
I tried a zillion times. Resetting, recompiling, etc. But no key... What am I missing here?

Log:
Starting pairing
[tesla_ble_vehicle:1057]: Not authenticated yet, building whitelist message
[tesla_ble_vehicle:1077]: Please tap your card on the reader now..
[ble_rssi_sensor:049]: ESP_GAP_BLE_READ_RSSI_COMPLETE_EVT RSSI: -44
[tesla_ble_vehicle:116]: [data update] Preparing command..
E (339596) tesla_ble: Session is not valid

Thank you!

**Comment by pvmil** [comment]
I also use a M5NanoC6, I was using the Yoziru several months ago succesfully but did not try it recently.
I am using this PedroKTFC version now, my config:

```
substitutions:
  name: tesla-ble-12345
  friendly_name: ESPHome Tesla BLE 12345
  charging_amps_max: "16"
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB

esp32:
  framework:
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

packages:
  PedroKTFC.esphome-tesla-ble: github://PedroKTFC/esphome-tesla-ble/tesla-ble-esp32-generic.dashboard.yml@dev

external_components:
  source: github://PedroKTFC/esphome-tesla-ble@dev```
  refresh: 0s # optional

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: <MyKey>

web_server:
  version: 3

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: !secret tesla_vin
  update_interval: 5s # default
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
    - multiply: 1.60934 # Convert miles to kms
  charge_state:
    name: "Charge level"
    unit_of_measurement: "%"
  battery_range:
    unit_of_measurement: "km"
    filters:
    - multiply: 1.60934 # Convert miles to kms

sensor:
  platform: ble_client
  type: rssi
  ble_client_id: ble_tesla_id
  name: "BLE Signal"
  icon: mdi:bluetooth
  update_interval: 10s
  entity_category: diagnostic

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret wifi_hotspot_password
```
