### ISSUE TITLE
Car presence binary sensor

### ISSUE THREAD

**Issue by nagyrobi** [PedroKTFC/esphome-tesla-ble#20]
I would find very useful a binary sensor to simply show if the car is nearby or not. This could be simply mirroring the state of the BLE connection: if it's connected, it's present, if it lost connection (with a configurable timeout), it's not present.

Use cases:
- I use a LVGL display with ESPHome, I'd like to update labels on a single trigger when car not present to something meaningful like (- or N/A), disable buttons etc, and re-enable them when car connects back
- Trigger garage door closing if left open after car goes away etc.

**Comment by PedroKTFC** [comment]
ble_disconnected_min_time. The readme is hopefully clear on the parameters.

**Comment by PedroKTFC** [comment]
Remember that when the BLE disconnects, it disconnects for everything.

**Comment by nagyrobi** [comment]
What do you think of this:
```yaml
binary_sensor:
  - platform: template
    name: Car at home
    id: is_tesla_present
    device_class: presence
    icon: mdi:car-connected

tesla_ble_vehicle:
  is_asleep:
    name: Car asleep
    id: tesla_is_asleep
    on_state:
      - lambda: |-
            if (!id(tesla_is_asleep).has_state()) {
              id(is_tesla_present).publish_state(false);
            } else {
              id(is_tesla_present).publish_state(true);
            }
```
