### ISSUE TITLE
can't get miles to convert to km

### ISSUE THREAD

**Issue by benjaminfrombe** [PedroKTFC/esphome-tesla-ble#47]
Exactly what I did, since I need to make modifications I'm wondering if I'm doing this right

cp tesla-ble.example.yml tesla-ble.yml

in that file I had to change 2 things: 
- change key xxxxxx to !secret api_encryption_key
- change name: ${name} to name: ${device_name}

then I needed to add in the tesla-ble-m5stack-nanoc6.dashboard.yml file (I don't understand why because it was already in my tesla-ble.yml, but otherwise it doesn't compile):

```
esphome:
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git #dev #v0.2.0
```

then the 'make compile tesla-ble.yml BOARD=m5stack-nanoc6' compiled

but after uploading I'm still seeing miles instead of km

Could use some help here ...

Thanks a lot !!

complete tesla-ble.yml:
```
substitutions:
  # all substitutions for this project
  espidf_version: 5.3.0
  platformio_version: 6.8.1
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://PedroKTFC/esphome-tesla-ble

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git

tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
```

**Comment by lukej0** [comment]
This is, how I got the m5stack nanoc6 working:
```
esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git
  
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.7.0.zip
    #board_build.f_cpu: 160000000L
    #board_build.f_flash: 80000000L
    #board_build.flash_size: 4MB
    #build_flags: "-DBOARD_HAS_PSRAM"
    #board_build.arduino.memory_type: qio_opi
    
web_server:
  version: 3

substitutions:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  name: tesla-ble
  friendly_name: "Tesla BLE v4"
  charging_amps_max: "16"
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

esp32:
  framework:
    type: esp-idf
    version: 5.2.1
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Board specific entities
light:
  - platform: status_led
    name: "Status LED"
    entity_category: diagnostic
    pin: GPIO7

  #G20=RGB WS2812
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO20
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    # rmt_channel: 1
    chipset: ws2812
    name: "RGB LED"
    entity_category: diagnostic
    power_supply: rgbpwr

power_supply:
  - id: 'rgbpwr'
    enable_on_boot: true
    pin: GPIO19
    enable_time: 10ms
    keep_on_time: 10ms

#G9=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  #manual_ip:
    #static_ip: XXX.XXX.XXX.XXX
    #gateway: XXX.XXX.XXX.XXX
    #subnet: XXX.XXX.XXX.XXX

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
 
external_components:
  - source: github://pedroktfc/esphome-tesla-ble
    refresh: 1h 

packages:
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml
  device_base: github://pedroktfc/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml
  # listener: github://pedroktfc/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

#dashboard_import:
  #package_import_url: github://pedroktfc/esphome-tesla-ble/tesla-ble-esp32-generic.dashboard.yml

tesla_ble_vehicle:
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
```

**Comment by benjaminfrombe** [comment]
ok, got it to work, this is my config: problem is that here and there includes from online sources are made ...

```
external_components: !include packages/external_components.yml

packages:
  base: !include packages/base.yml
  device_base: !include boards/m5stack-nanoc6.yml
  client: !include packages/client.yml

#dashboard_import:
#  package_import_url: github://PedroKTFC/esphome-tesla-ble/tesla-ble-m5stack-nanoc6.dashboard.yml


esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git

tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
```
