### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by J6ole** [PedroKTFC/esphome-tesla-ble#56]
Hello

I'm trying to install esphome-tesla-ble using the script from the GoogleDocs step by step guide.

I am using a M5NanoC6 and so have adjusted the YAML accordingly.

YAML Code and install logs shown below.

Any advice on how to solve these install errors gratefully received.

Thank you

Justin

**YAML Code**

```
substitutions:
  # all substitutions for this project
  espidf_version: 5.3.1
  platformio_version: 6.9.0
  friendly_name: Tesla BLE F549C4
  device_name: tesla-ble-f549c4
  device_description: Tesla WAS
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

esp32:
  framework:
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

api:
  encryption:
    key: !secret api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


external_components:
  source: github://PedroKTFC/esphome-tesla-ble@dev


packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml@dev
  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml@dev
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml@dev
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address


esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev


tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknown (s)

```
**When I install fro ESPHOME Builder (dev) then I get the following log**

Log file is as follows with errors:

```
INFO ESPHome 2025.6.0-dev
INFO Reading configuration /config/esphome/esphome-web-1fbbe0.yaml...
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Detected timezone 'Europe/London'
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.8.2
INFO Compiling app...
Processing tesla-ble-f549c4 (board: esp32-c6-devkitm-1; framework: espidf; platform: platformio/espressif32@6.9.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C6 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50301.0 (5.3.1) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 13.2.0+20240530
Reading CMake configuration...
[nanopb] No generation needed.
[nanopb] No generation needed.
Dependency Graph
|-- TeslaBLE @ 2.2.1+sha.bc0c3ed
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/core/application.cpp.o
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/core/component.cpp.o
In file included from src/esphome/components/sensor/sensor.h:3,
                 from src/esphome/core/application.h:20,
                 from src/esphome/core/application.cpp:1:
src/esphome/core/application.cpp: In member function 'void esphome::Application::teardown_components(uint32_t)':
src/esphome/core/application.cpp:222:21: error: format '%u' expects argument of type 'unsigned int', but argument 6 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  222 |       ESP_LOGW(TAG, "%s did not complete teardown within %u ms", component->get_component_source(), timeout_ms);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:76:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
   76 | #define ESPHOME_LOG_FORMAT(format) format
      |                                    ^~~~~~
src/esphome/core/log.h:154:28: note: in expansion of macro 'esph_log_w'
  154 | #define ESP_LOGW(tag, ...) esph_log_w(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/core/application.cpp:222:7: note: in expansion of macro 'ESP_LOGW'
  222 |       ESP_LOGW(TAG, "%s did not complete teardown within %u ms", component->get_component_source(), timeout_ms);
      |       ^~~~~~~~
src/esphome/core/application.cpp:222:59: note: format string is defined here
  222 |       ESP_LOGW(TAG, "%s did not complete teardown within %u ms", component->get_component_source(), timeout_ms);
      |                                                          ~^
      |                                                           |
      |                                                           unsigned int
      |                                                          %lu
cc1plus: some warnings being treated as errors
*** [.pioenvs/tesla-ble-f549c4/src/esphome/core/application.cpp.o] Error 1
========================= [FAILED] Took 36.44 seconds =========================
```
