### ISSUE TITLE
OTA Update not possible for current dev version (M5Stack NanoC6)

### ISSUE THREAD

**Issue by lukej0** [PedroKTFC/esphome-tesla-ble#60]
Hi, I tried update to the current dev version. Compiling and everything went fine, but when it comes to uploading, the process ends with an error:
```
INFO Uploading /data/build/tesla-ble/.pioenvs/tesla-ble/firmware.bin (1836400 bytes)
ERROR Error binary size: Error: The OTA partition on the ESP is too small. ESPHome needs to resize this partition, please flash over USB.
```
The patition only has 1835008 bytes available
```
RAM:   [==        ]  16.0% (used 52368 bytes from 327680 bytes)
Flash: [==========]  99.8% (used 1832252 bytes from 1835008 bytes)
```

The current installed version is the main version.
Don't know if you could do anything about the size but I thought I might try.

**Comment by PedroKTFC** [comment]
My build gives me the following. I'm guessing your board must use some different dependencies that makes your build bigger. I don't know if there's a way of reducing the size.

```
RAM:   [==        ]  18.5% (used 60648 bytes from 327680 bytes)
Flash: [========  ]  83.8% (used 1537664 bytes from 1835008 bytes)
========================= [SUCCESS] Took 63.26 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.172 port 3232...
INFO Connected to 192.168.1.172
INFO Uploading /data/build/tesla-ble-2e1480/.pioenvs/tesla-ble-2e1480/firmware.bin (1538032 bytes)

```

**Comment by lukej0** [comment]
I tried flashing via USB but unfortunately that didn't work either. It went in boot-loop with the following error-message:
```
[20:07:34]E (497) esp_image: Image length 1837456 doesn't fit in partition length 1835008
[20:07:34]E (498) boot: OTA app partition slot 0 is not bootable
[20:07:34]E (504) esp_image: image at 0x1d0000 has invalid magic byte (nothing flashed here?)
[20:07:34]E (512) boot: OTA app partition slot 1 is not bootable
[20:07:34]E (518) boot: No bootable app partitions in the partition table
```

Perhaps when I come home today I might try some things. I will come back at this to inform you about the progress
@PedroKTFC are you also using the M5Stack NanoC6?

**Comment by PedroKTFC** [comment]
I have a pretty basic board. This is my yaml:
```
substitutions:
# all substitutions for this project
  name: tesla-ble-2e1480
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Tesla BLE
  board: esp32dev
  variant: esp32
  flash_size: 4MB
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

esp32:
  board: node32s
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: "6.9.0"

external_components:
  - source:
      type: git
      url: https://github.com/PedroKTFC/esphome-tesla-ble
    refresh: 0s
    components: [tesla_ble_vehicle] #, tesla_ble_listener]

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml 
#  device_base: github://PedroKTFC/esphome-tesla-ble/boards/esp32-generic.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml 
#  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml@dev # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git #@dev #v0.2.0

tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)

api:
  encryption:
    key: blahhhh

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 10s
    entity_category: diagnostic

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.172
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password
  # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
  on_connect:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

```

**Comment by PedroKTFC** [comment]
Have you tried version 5.3.0 instead of 5.3.1?

**Comment by mr-p666** [comment]
It should help, if you create your own base.yml without the captive_portal.
Or maybe @PedroKTFC could exclude it from the base.yml because in my opinion it's not something necessary that you need in daily life in combination with HA, but for debugging reasons only.

**Comment by top-gun** [comment]
Fwiw, there is an option for the compiler to optimize for size.  This might help:

```
esphome:
(...)
  platformio_options:
    build_flags:
      - -Os
```

**Comment by top-gun** [comment]
> The build_flags seemed to have no impact unfortunately. After the test with the build flags I then tried the dev branch again and this time the size fitted (almost exactly). 1831664 of 1835008 bytes

Suggestion: Don't use a -C6, get a -S3 with 8MB of flash and you'll be fine for many years. Those gadgets cost next to nothing. Yes, the -C6 has BT5. So does the -S3. And your car is still BT 4.1.

**Comment by lukej0** [comment]
I only got the C6 because it was mentioned in yozirus project as the board on which it was tested. So I thought it might be the best choice for somebody like me who had no clue of the esp32 world.
As mentioned earlier, I already ordered a different board (an S3 with a display I hope to get working for showing me the actual state of charge and charge current).

So I might close the issue tomorrow, if nobody has further information or approaches to try.

**Comment by PedroKTFC** [comment]
Post your yaml as there might be an obvious solution we haven't spotted without it.

**Comment by lukej0** [comment]
That's my yaml
```
esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  libraries:
    https://github.com/PedroKTFC/tesla-ble.git#dev
    
web_server:
  version: 3

substitutions:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  name: tesla-ble
  friendly_name: "Tesla BLE v4"
  charging_amps_max: "16"
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

esp32:
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Board specific entities
light:
  - platform: status_led
    name: "Status LED"
    entity_category: diagnostic
    pin: GPIO7

  #G20=RGB WS2812
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO20
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    # rmt_channel: 1
    chipset: ws2812
    name: "RGB LED"
    entity_category: diagnostic
    power_supply: rgbpwr

power_supply:
  - id: 'rgbpwr'
    enable_on_boot: true
    pin: GPIO19
    enable_time: 10ms
    keep_on_time: 10ms

#G9=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.127
    gateway: 192.168.178.1
    subnet: 255.255.255.0

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

external_components:
  - source: github://pedroktfc/esphome-tesla-ble@dev
    refresh: 1h 

packages:
  base: github://pedroktfc/esphome-tesla-ble/packages/base.yml@dev
  client: github://pedroktfc/esphome-tesla-ble/packages/client.yml@dev

tesla_ble_vehicle:
  odometer:
    name: "Odometer"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknown (s)
```

**Comment by PedroKTFC** [comment]
You are using some old versions of esp version and platform version. 5.3.1 and 6.9.0 would be more expected. I recently tried @top-gun suggestion which built for me:
```
esp32:
  board: esp32dev  # oder ein anderes passendes Board
  framework:
    type: esp-idf
    version: 5.3.2
```
